ALTER TABLE "Schema"."ENTITY1" DROP CONSTRAINT "ENTITY1_PK" CASCADE;

ALTER TABLE "Schema"."ENTITY1" ADD COLUMN "ATTRIBUTE3" CHAR(5);

COMMENT ON COLUMN "Schema"."ENTITY1"."ATTRIBUTE4" IS
'This is test on 21st May 2018';

