ALTER TABLE "Schema"."ENTITY1" DROP CONSTRAINT "ENTITY1_PK" CASCADE;

ALTER TABLE "Schema"."ENTITY1" DROP COLUMN "ATTRIBUTE4" CASCADE;

ALTER TABLE "Schema"."ENTITY1" ADD COLUMN "ATTRIBUTE3" CHAR(5);

