-- Renaming table to maintain a backup;

ALTER TABLE "Schema"."ENTITY1" RENAME TO "ENTITY1_BU0";

ALTER TABLE "Schema"."ENTITY1" ADD COLUMN "ATTRIBUTE3" CHAR(5);

CREATE TABLE "Schema"."ENTITY1" (
		"ATTRIBUTE1" CHAR(5),
		"ATTRIBUTE2" CHAR(5),
		"ATTRIBUTE3" CHAR(5)
	)
	DISTRIBUTE ON RANDOM;

